### ISSUE TITLE
Error while converting siemens tar archives of dicom files to nifti with nimsdata in docker

### ISSUE THREAD

**Issue by Youguang** [vistalab/scitran-data#30]
`sudo docker run -t -i -v /home/z/test/y05/tarfiles/:/data vistalab/nimsdata nimsdata -p dicom -w nifti --writer_kwarg voxel_order=LPS -i /data/1.3.12.2.1107.5.2.43.67028.30000017053023571472700000094_1_18_dicoms.tgz /data/nifti_from_dicom`

> Traceback (most recent call last):
>   File "/var/local/nimsdata/nimsdata.py", line 750, in <module>
>     ds = nimsdata.parse(args.input, load_data=True, ignore_json=args.ignore_json, filetype=args.parser, **p_kwargs)
>   File "/var/local/nimsdata/nimsdata.py", line 388, in parse
>     ds = nimsparser(path, load_data, **kwargs)
>   File "/var/local/nimsdata/medimg/nimsdicom.py", line 242, in __init__
>     self.load_data()
>   File "/var/local/nimsdata/medimg/nimsdicom.py", line 294, in load_data
>     self.parse_all()  # COMPOSED; parses mfr sop specifics
>   File "/var/local/nimsdata/medimg/dcm/mr/siemens.py", line 143, in parse_all
>     self.num_timepoints = self.total_num_slices / self.num_slices
> TypeError: unsupported operand type(s) for /: 'int' and 'NoneType'

**Comment by Youguang** [comment]
`docker run -t -i -v /home/z/test/:/data vistalab/nimsdata siemens_multicoil /data/1.3.12.2.1107.5.2.43.67028.30000017053023571472700000094_1_15_1_dicoms.tgz /data/1.3.12.2.1107.5.2.43.67028.30000017053023571472700000094_1_15_2_dicoms.tgz -o combined_tar1_tar2.nii.gz`

> Traceback (most recent call last):
>   File "/var/local/nimsscripts/siemens_multicoil.py", line 163, in <module>
>     n.process()
>   File "/var/local/nimsscripts/siemens_multicoil.py", line 77, in process
>     dcm_ds = nimsdata.parse(fpath, filetype='dicom', load_data=True, ignore_json=True)
>   File "/var/local/nimsdata/nimsdata.py", line 388, in parse
>     ds = nimsparser(path, load_data, **kwargs)
>   File "/var/local/nimsdata/medimg/nimsdicom.py", line 242, in __init__
>     self.load_data()
>   File "/var/local/nimsdata/medimg/nimsdicom.py", line 294, in load_data
>     self.parse_all()  # COMPOSED; parses mfr sop specifics
>   File "/var/local/nimsdata/medimg/dcm/mr/siemens.py", line 143, in parse_all
>     self.num_timepoints = self.total_num_slices / self.num_slices
> TypeError: unsupported operand type(s) for /: 'int' and 'NoneType'
>
